In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("../data/HU3_medicamentos_diabetes.xlsx")
df.shape

(1569, 32)

In [3]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
nregistro,1569.0,7.602104e+07,2.759623e+08,3.155600e+04,7.658700e+04,8.803000e+04,9.128400e+04,1.252000e+09
cn,1568.0,7.248901e+05,6.261735e+04,6.002210e+05,6.776678e+05,7.290610e+05,7.648212e+05,9.998530e+05
estado_aut,1569.0,1.459378e+12,2.856038e+11,-3.420612e+11,1.258585e+12,1.557266e+12,1.699009e+12,1.790187e+12
estado_rev,228.0,1.718252e+12,4.807024e+10,1.633453e+12,1.676474e+12,1.725194e+12,1.767871e+12,1.787906e+12
comercializado,1569.0,4.964946e-01,5.001471e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
requiere_receta,1569.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
generico,1569.0,7.654557e-01,4.238488e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
afecta_conduccion,1569.0,4.448693e-01,4.971098e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00
triangulo_negro,1569.0,2.103250e-02,1.435384e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
medicamento_huerfano,1569.0,1.274697e-03,3.569152e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
biosimilar,1569.0,2.549395e-03,5.044320e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
num_registros_atc,1569.0,2.998725e+00,3.569152e-02,2.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00
num_principios_activos,1569.0,1.135755e+00,3.426377e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00
num_excipientes,1569.0,2.033779e+00,1.183219e+00,0.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,9.000000e+00
numero_tablas,1569.0,5.808795e+00,6.954051e+00,0.000000e+00,1.000000e+00,3.000000e+00,1.000000e+01,3.500000e+01
indicador_riesgo_severo,1569.0,1.277247e+01,6.913356e+00,1.000000e+00,8.000000e+00,1.200000e+01,1.700000e+01,3.800000e+01
Código Nacional,827.0,7.161334e+05,6.496970e+04,6.502920e+05,6.653895e+05,7.031750e+05,7.333395e+05,9.998530e+05
Precio de venta al público con IVA,827.0,2.029904e+01,2.318083e+01,9.500000e-01,4.170000e+00,1.118000e+01,2.793500e+01,1.334700e+02
Precio de referencia,686.0,1.344268e+01,1.302407e+01,9.500000e-01,3.870000e+00,8.340000e+00,1.997000e+01,1.012400e+02

In [4]:
df[(df['cn'].isnull()) & (~df['Código Nacional'].isnull())]

Empty DataFrame
Columns: [nregistro, nombre, pactivos, labtitular, labcomercializador, cn, dosis, forma_farmaceutica_simplificada, estado_aut, estado_rev, comercializado, requiere_receta, generico, afecta_conduccion, triangulo_negro, medicamento_huerfano, biosimilar, url_html_ficha_tecnica, url_foto_materiales, num_registros_atc, num_principios_activos, num_excipientes, vias_administracion, palabras_seccion_4_4, numero_tablas, indicador_riesgo_severo, Código Nacional, Estado, Precio de venta al público con IVA, Precio de referencia, Tratamiento de larga duración, Especial control médico]
Index: []

[0 rows x 32 columns]

In [5]:
df[(~df['cn'].isnull()) & (df['Código Nacional'].isnull())]
#hemos decidido que vamos a quitarnos todos los medicamentos cuyo cn tiene codigo nacional null porque no tienen precio de venta y entonces hemos decidido que no nos interesa

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,vias_administracion,palabras_seccion_4_4,numero_tablas,indicador_riesgo_severo,Código Nacional,Estado,Precio de venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
3,2230003,ACTRAPID 100 UI/ML SOLUCION INYECTABLE EN UN VIAL,INSULINA SOLUBLE NEUTRA,Novo Nordisk A/S,Novo Nordisk Pharma S.A.,775502.0,100 U/ml,INYECTABLE,1060034400000,NaN,...,"VÍA INTRAVENOSA, VÍA SUBCUTÁNEA",772,1,2,NaN,NaN,NaN,NaN,NaN,NaN
4,89508,BIGETRA 110 MG CAPSULAS DURAS EFG,DABIGATRAN ETEXILATO MESILATO,Adamed Laboratorios S.L.U.,Adamed Laboratorios S.L.U.,764777.0,110 mg,CAPSULA,1713779047000,1.785998e+12,...,VÍA ORAL,2885,30,14,NaN,NaN,NaN,NaN,NaN,NaN
11,61470,CAPTOPRIL NORMON 25 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorios Normon S.A.,Laboratorios Normon S.A.,649459.0,Captopril 25 mg,COMPRIMIDO,862437600000,NaN,...,VÍA ORAL,2404,1,6,NaN,NaN,NaN,NaN,NaN,NaN
13,61572,CAPTOPRIL STADA 25 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorio Stada S.L.,Laboratorio Stada S.L.,600221.0,25 mg,COMPRIMIDO,873064800000,1.707916e+12,...,VÍA ORAL,1707,2,3,NaN,NaN,NaN,NaN,NaN,NaN
20,64971,COZAAR 100 mg COMPRIMIDOS RECUBIERTOS CON PELI...,LOSARTAN POTASICO,Organon Salud S.L.,Organon Salud S.L.,809186.0,100 mg losartan potasico,COMPRIMIDO,1028757600000,NaN,...,VÍA ORAL,1176,1,11,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1561,89607,XARIVA 20 MG CAPSULAS DURAS EFG,RIVAROXABAN,Kern Pharma S.L.,Kern Pharma S.L.,765038.0,20 mg,CAPSULA,1716986221000,NaN,...,VÍA ORAL,1727,14,21,NaN,NaN,NaN,NaN,NaN,NaN
1562,7382018,XELEVIA 100 MG COMPRIMIDOS RECUBIERTOS CON PEL...,SITAGLIPTINA,Merck Sharp & Dohme B.V.,Merck Sharp & Dohme De Espana S.A.,602940.0,100 mg,COMPRIMIDO,1208728800000,NaN,...,VÍA ORAL,450,3,18,NaN,NaN,NaN,NaN,NaN,NaN
1563,114947003,"XULTOPHY 100 U/ML + 3,6 MG/ML SOLUCION INYECTABLE","LIRAGLUTIDA, INSULINA DEGLUDEC",Novo Nordisk A/S,Novo Nordisk Pharma S.A.,704321.0,"100 unidades/ 3,6 mg por ml",INYECTABLE,1416870000000,NaN,...,VÍA SUBCUTÁNEA,1156,8,19,NaN,NaN,NaN,NaN,NaN,NaN
1564,89973,ZEDILARF 10 MG COMPRIMIDOS RECUBIERTOS CON PEL...,DAPAGLIFLOZINA PROPANODIOL MONOHIDRATO,Pharmapath S.A.,Pharmapath S.A.,766348.0,10 mg,COMPRIMIDO,1732536796000,NaN,...,VÍA ORAL,1146,10,36,NaN,NaN,NaN,NaN,NaN,NaN
1565,89974,ZEDILARF 5 MG COMPRIMIDOS RECUBIERTOS CON PELÍ...,DAPAGLIFLOZINA PROPANODIOL MONOHIDRATO,Pharmapath S.A.,Pharmapath S.A.,766349.0,5 mg,COMPRIMIDO,1732536795000,NaN,...,VÍA ORAL,1146,10,36,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df[(df['Precio de referencia'].isnull()) & (~df['Precio de venta al público con IVA'].isnull())]

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,vias_administracion,palabras_seccion_4_4,numero_tablas,indicador_riesgo_severo,Código Nacional,Estado,Precio de venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
2,2230011,ACTRAPID INNOLET 100 UI/ML SOLUCION INYECTABLE...,INSULINA SOLUBLE NEUTRA,Novo Nordisk A/S,Novo Nordisk Pharma S.A.,775536.0,100 U/ml,INYECTABLE,973465200000,NaN,...,"VÍA INTRAVENOSA, VÍA SUBCUTÁNEA",772,1,2,775536.0,BAJA POR NO COMERCIALIZAR,35.89,NaN,SI,NO
6,111696003,BYDUREON 2 MG POLVO Y DISOLVENTE PARA SUSPENSI...,EXENATIDA,Astrazeneca Ab,Astrazeneca Farmaceutica Spain S.A.,703897.0,2 MG,INYECTABLE,1413756000000,1.767871e+12,...,VÍA SUBCUTÁNEA,829,7,11,703897.0,BAJA GENERAL,93.34,NaN,NO,NO
7,6362003,BYETTA 10 MICROGRAMOS SOLUCION INYECTABLE EN P...,EXENATIDA,Astrazeneca Ab,Astrazeneca Farmaceutica Spain S.A.,658304.0,"0,25 mg",INYECTABLE,1175637600000,1.767871e+12,...,VÍA SUBCUTÁNEA,712,2,8,658304.0,BAJA GENERAL,133.47,NaN,NO,NO
8,6362001,BYETTA 5 MICROGRAMOS SOLUCION INYECTABLE EN PL...,EXENATIDA,Astrazeneca Ab,Astrazeneca Farmaceutica Spain S.A.,658301.0,"0,25 mg",INYECTABLE,1175637600000,1.767871e+12,...,VÍA SUBCUTÁNEA,712,2,8,658301.0,BAJA GENERAL,66.74,NaN,NO,NO
36,1151051009,EBYMECT 5 MG/1.000 MG COMPRIMIDOS RECUBIERTOS ...,"DAPAGLIFLOZINA, METFORMINA HIDROCLORURO",Astrazeneca Ab,Laboratorio Tau S.A.,709156.0,5mg /1.000 mg,COMPRIMIDO,1449615600000,NaN,...,VÍA ORAL,1977,9,23,709156.0,ALTA,48.74,NaN,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1447,6366018,TANDEMACT 30 mg/2 mg COMPRIMIDOS,"PIOGLITAZONA, GLIMEPIRIDA",Cheplapharm Arzneimittel Gmbh,Laboratorios Rubio S.A.,663162.0,30 gm de pioglitazona + 2 mg de glimepirida,COMPRIMIDO,1254175200000,NaN,...,VÍA ORAL,25,1,10,663162.0,ALTA,56.46,NaN,NO,NO
1448,6366006,TANDEMACT 30 mg/4 mg COMPRIMIDOS,"PIOGLITAZONA, GLIMEPIRIDA",Cheplapharm Arzneimittel Gmbh,Laboratorios Rubio S.A.,663163.0,30 mg de pioglitazona + 4 mg de glimepirida,COMPRIMIDO,1254175200000,NaN,...,VÍA ORAL,1593,1,10,663163.0,ALTA,59.95,NaN,NO,NO
1497,114956002,"TRULICITY 0,75 mg SOLUCION INYECTABLE EN PLUMA...",DULAGLUTIDA,Eli Lilly Nederland B.V.,Lilly S.A.,704633.0,"0,75 mg",INYECTABLE,1418598000000,NaN,...,VÍA SUBCUTÁNEA,451,13,31,704633.0,ALTA,128.15,NaN,NO,NO
1498,114956007,"TRULICITY 1,5 mg SOLUCION INYECTABLE EN PLUMA ...",DULAGLUTIDA,Eli Lilly Nederland B.V.,Lilly S.A.,704632.0,"1,5 mg",INYECTABLE,1418598000000,NaN,...,VÍA SUBCUTÁNEA,451,13,31,704632.0,ALTA,128.15,NaN,NO,NO
1553,113843005,"VIPDOMET 12,5 MG/850 MG COMPRIMIDOS RECUBIERTO...","ALOGLIPTINA, METFORMINA HIDROCLORURO",Takeda Pharma A/S,Laboratorios Menarini S.A.,701205.0,"12,5 mg/850 mg",COMPRIMIDO,1389826800000,NaN,...,VÍA ORAL,1248,5,15,701205.0,ALTA,48.96,NaN,NO,NO

In [7]:
df[(~df['Precio de referencia'].isnull()) & (~df['Precio de venta al público con IVA'].isnull())]

#cargarnos precio de referencia porque hay algunos que son nulos y los que no son nulos son siempre iguales que el precio de venta al público con IVA. Por lo tanto, podemos eliminar la columna de precio de referencia.
#el precio de referencia nunca existe sin el de venta, y cuando existe es igual a él

,nregistro,nombre,pactivos,labtitular,labcomercializador,cn,dosis,forma_farmaceutica_simplificada,estado_aut,estado_rev,...,vias_administracion,palabras_seccion_4_4,numero_tablas,indicador_riesgo_severo,Código Nacional,Estado,Precio de venta al público con IVA,Precio de referencia,Tratamiento de larga duración,Especial control médico
0,70452,ACARBOSA TECNIGEN 100 mg COMPRIMIDOS,ACARBOSA,Tecnimede España Industria Farmaceutica S.A.,Tecnimede España Industria Farmaceutica S.A.,662260.0,100 mg,COMPRIMIDO,1233788400000,NaN,...,VÍA ORAL,149,1,2,662260.0,ALTA,15.30,15.30,SI,NO
1,70451,ACARBOSA TECNIGEN 50 mg COMPRIMIDOS,ACARBOSA,Tecnimede España Industria Farmaceutica S.A.,Tecnimede España Industria Farmaceutica S.A.,662258.0,50 mg,COMPRIMIDO,1233788400000,NaN,...,VÍA ORAL,149,1,2,662258.0,ALTA,7.65,7.65,SI,NO
5,89509,BIGETRA 150 MG CAPSULAS DURAS,DABIGATRAN ETEXILATO MESILATO,Adamed Laboratorios S.L.U.,Adamed Laboratorios S.L.U.,764780.0,150 mg,CAPSULA,1713779048000,1.785998e+12,...,VÍA ORAL,2813,25,12,764780.0,BAJA GENERAL,45.08,45.08,NO,NO
9,62304,CAPTOPRIL CINFA 25 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,706317.0,25 mg captopril,COMPRIMIDO,909874800000,NaN,...,VÍA ORAL,2475,1,8,706317.0,ALTA,3.53,3.53,SI,NO
10,62305,CAPTOPRIL CINFA 50 mg COMPRIMIDOS EFG,CAPTOPRIL,Laboratorios Cinfa S.A.,Laboratorios Cinfa S.A.,706341.0,50 mg captopril,COMPRIMIDO,909874800000,NaN,...,VÍA ORAL,2475,1,8,706341.0,ALTA,3.53,3.53,SI,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,90125,VILDAGLIPTINA/METFORMINA VIVANTA 50 MG/1 000 M...,"VILDAGLIPTINA, METFORMINA HIDROCLORURO",Vivanta Generics S.R.O.,Mabo Farma S.A.,766878.0,50 mg/1.000 mg,COMPRIMIDO,1764930254000,NaN,...,VÍA ORAL,1055,2,7,766878.0,ALTA,36.19,36.19,NO,NO
1548,90126,VILDAGLIPTINA/METFORMINA VIVANTA 50 MG/850 MG ...,"VILDAGLIPTINA, METFORMINA HIDROCLORURO",Vivanta Generics S.R.O.,Mabo Farma S.A.,766888.0,50 mg/850 mg,COMPRIMIDO,1764930254000,NaN,...,VÍA ORAL,1055,2,7,766888.0,ALTA,36.19,36.19,NO,NO
1566,59127,ZESTRIL 20 mg COMPRIMIDOS,LISINOPRIL,Atnahs Pharma Netherlands Bv.,Atnahs Pharma Netherlands Bv.,865287.0,20 mg lisinopril,COMPRIMIDO,678319200000,NaN,...,VÍA ORAL,2100,1,10,865287.0,ALTA,6.35,6.35,SI,NO
1567,8483009,ZOMARIST 50 mg/1000 mg COMPRIMIDOS RECUBIERTOS...,"METFORMINA HIDROCLORURO, VILDAGLIPTINA",Novartis Europharm Limited,Esteve Pharmaceuticals S.A.,662085.0,1000/50 mg/mg,COMPRIMIDO,1231455600000,NaN,...,VÍA ORAL,1054,2,7,662085.0,ALTA,36.19,36.19,NO,NO
1568,8483003,ZOMARIST 50 mg/850 mg COMPRIMIDOS RECUBIERTOS ...,"METFORMINA HIDROCLORURO, VILDAGLIPTINA",Novartis Europharm Limited,Esteve Pharmaceuticals S.A.,662084.0,850/50 mg/mg,COMPRIMIDO,1231455600000,NaN,...,VÍA ORAL,1054,2,7,662084.0,ALTA,36.19,36.19,NO,NO

In [8]:
#cargarnos precio de referencia porque hay algunos que son nulos y los que no son nulos son siempre iguales que el precio de venta al público con IVA. Por lo tanto, podemos eliminar la columna de precio de referencia.
#el precio de referencia nunca existe sin el de venta, y cuando existe es igual a él
df_clean = df.copy()
df_clean = df_clean.dropna(subset=["Código Nacional"])
print(df_clean.shape)

(827, 32)

In [9]:
df[(~df['Precio de referencia'].isnull()) & (df['Precio de venta al público con IVA'].isnull())]

Empty DataFrame
Columns: [nregistro, nombre, pactivos, labtitular, labcomercializador, cn, dosis, forma_farmaceutica_simplificada, estado_aut, estado_rev, comercializado, requiere_receta, generico, afecta_conduccion, triangulo_negro, medicamento_huerfano, biosimilar, url_html_ficha_tecnica, url_foto_materiales, num_registros_atc, num_principios_activos, num_excipientes, vias_administracion, palabras_seccion_4_4, numero_tablas, indicador_riesgo_severo, Código Nacional, Estado, Precio de venta al público con IVA, Precio de referencia, Tratamiento de larga duración, Especial control médico]
Index: []

[0 rows x 32 columns]

In [10]:

df_clean = df_clean.drop(columns=["Precio de referencia"])

df[(~df['Precio de referencia'].isnull()) & (~df['Precio de venta al público con IVA'].isnull())]

In [11]:
df.describe(include='object').T
#vamos a mirar todas las columnas escritas para encontrar cosas a saltar

,count,unique,top,freq
nombre,1569,1525,LANTUS 100 UNIDADES/ML SOLUCION INYECTABLE EN ...,5
pactivos,1569,115,RIVAROXABAN,114
labtitular,1569,141,Laboratorios Cinfa S.A.,73
labcomercializador,1569,139,Teva Pharma S.L.U.,91
dosis,1569,249,5 mg,110
forma_farmaceutica_simplificada,1569,8,COMPRIMIDO,1302
url_html_ficha_tecnica,1569,1569,https://cima.aemps.es/cima/dochtml/ft/08483003...,1
url_foto_materiales,389,389,https://cima.aemps.es/cima/fotos/thumbnails/ma...,1
vias_administracion,1569,7,VÍA ORAL,1425
palabras_seccion_4_4,1569,611,450,19
Estado,827,4,ALTA,665
Tratamiento de larga duración,827,2,NO,551
Especial control médico,827,1,NO,827

In [12]:
df['Estado'].value_counts()

Estado
ALTA                           665
BAJA GENERAL                    99
BAJA POR NO COMERCIALIZAR       56
SUSPENSION TEMPORAL GENERAL      7
Name: count, dtype: int64

In [13]:
df['Especial control médico'].value_counts()

Especial control médico
NO    827
Name: count, dtype: int64

In [14]:
df['dosis'].value_counts()
#tenemos que limpiar los valores "sucios" para quitar las columnas unicas que no tienen sentido

dosis
5 mg                           110
50 mg                          101
20 mg                           86
100 mg                          70
15 mg                           65
                              ...
50mg/850mg                       1
50 mg / 1000 mg                  1
7,2 mg                           1
100 unidades/ 3,6 mg por ml      1
850/50 mg/mg                     1
Name: count, Length: 249, dtype: int64

In [15]:
df['vias_administracion'].value_counts()

#podriamos unir las columnas VÍA INTRAMUSCULAR, VÍA SUBCUTÁNEA y VÍA INTRAMUSCULAR, VÍA INTRAVENOSA, VÍA SUBCUTÁNEA

vias_administracion
VÍA ORAL                                              1425
VÍA SUBCUTÁNEA                                         113
VÍA INTRAVENOSA, VÍA SUBCUTÁNEA                         11
VÍA SUBLINGUAL                                           9
VÍA INTRAMUSCULAR, VÍA SUBCUTÁNEA                        5
VÍA INTRAMUSCULAR, VÍA INTRAVENOSA, VÍA SUBCUTÁNEA       3
VÍA NASAL                                                3
Name: count, dtype: int64

In [16]:
#Renombrar columnas
df_clean = df_clean.rename(columns={
    "Código Nacional": "codigo_nacional_nomenclator",
    "Estado": "estado",
    "Precio de venta al público con IVA": "precio_pvp_iva",
    "Tratamiento de larga duración": "tratamiento_larga_duracion",
    "Especial control médico": "especial_control_medico",
})
df_clean.columns

Index(['nregistro', 'nombre', 'pactivos', 'labtitular', 'labcomercializador',
       'cn', 'dosis', 'forma_farmaceutica_simplificada', 'estado_aut',
       'estado_rev', 'comercializado', 'requiere_receta', 'generico',
       'afecta_conduccion', 'triangulo_negro', 'medicamento_huerfano',
       'biosimilar', 'url_html_ficha_tecnica', 'url_foto_materiales',
       'num_registros_atc', 'num_principios_activos', 'num_excipientes',
       'vias_administracion', 'palabras_seccion_4_4', 'numero_tablas',
       'indicador_riesgo_severo', 'codigo_nacional_nomenclator', 'estado',
       'precio_pvp_iva', 'tratamiento_larga_duracion',
       'especial_control_medico'],
      dtype='object')

In [ ]:
# Eliminar codigo_nacional_nomenclator y dejar solo cn
print((df_clean["cn"] == df_clean["codigo_nacional_nomenclator"]).all())
df_clean = df_clean.drop(columns=["codigo_nacional_nomenclator"])

True

In [25]:
df_clean["triangulo_negro"].value_counts()

triangulo_negro
0    827
Name: count, dtype: int64

In [28]:
df_clean["requiere_receta"].value_counts()

requiere_receta
1    827
Name: count, dtype: int64

In [29]:
df_clean["medicamento_huerfano"].value_counts()

medicamento_huerfano
0    827
Name: count, dtype: int64

In [30]:
df_clean["especial_control_medico"].value_counts()

especial_control_medico
NO    827
Name: count, dtype: int64

In [ ]:
# Como los valores de las columnas, de las secciones superiores, siempre tienen el mismo valor tras limpiar el dataset podemos eliminarlaas para simplificar
df_clean = df_clean.drop(columns=[
    "requiere_receta", "medicamento_huerfano", "triangulo_negro", "especial_control_medico",
])

requiere_receta -> [1]
triangulo_negro -> [0]
medicamento_huerfano -> [0]
especial_control_medico -> ['NO']

In [ ]:
# estado_rev tiene un 88 % de nulos, así que no tiene sentido rellenar fechas inventadas.
# En su lugar guardamos solo si el medicamento tiene revisión (1) o no (0).
df_clean["tiene_revision"] = 0                                              # creamos la columna con 0 en todas las filas
df_clean.loc[df_clean["estado_rev"].notna(), "tiene_revision"] = 1         # ponemos 1 solo en las filas donde estado_rev tiene una fecha (no es nulo)
# sirve para elegir qué filas y qué columna quieres leer o modificar (df.loc[filas, columna] = valor)
# df_clean["estado_rev"].notna() crea una lista de True/False, una por fila. Vale True cuando estado_rev tiene una fecha y False cuando está vacío. Esa es la parte de las filas.
# "tiene_revision" es la columna que quieres cambiar.
# = 1 es el valor que se escribe en las filas que dieron True.


# Con url_foto_materiales pasa lo mismo, la URL en sí no nos sirve, solo saber si existe o no.
df_clean["tiene_foto_materiales"] = 0                                       # creamos la columna con 0 en todas las filas
df_clean.loc[df_clean["url_foto_materiales"].notna(), "tiene_foto_materiales"] = 1   # ponemos 1 solo donde hay URL de foto

# Ya tenemos la información en las columnas 0/1, así que borramos las originales.
df_clean = df_clean.drop(columns=["estado_rev", "url_foto_materiales"])

In [32]:
df_clean["url_html_ficha_tecnica"].value_counts()

url_html_ficha_tecnica
https://cima.aemps.es/cima/dochtml/ft/08483003/FT_08483003.html    1
https://cima.aemps.es/cima/dochtml/ft/70452/FT_70452.html          1
https://cima.aemps.es/cima/dochtml/ft/70451/FT_70451.html          1
https://cima.aemps.es/cima/dochtml/ft/02230011/FT_02230011.html    1
https://cima.aemps.es/cima/dochtml/ft/89509/FT_89509.html          1
                                                                  ..
https://cima.aemps.es/cima/dochtml/ft/71704/FT_71704.html          1
https://cima.aemps.es/cima/dochtml/ft/71619/FT_71619.html          1
https://cima.aemps.es/cima/dochtml/ft/71372/FT_71372.html          1
https://cima.aemps.es/cima/dochtml/ft/72672/FT_72672.html          1
https://cima.aemps.es/cima/dochtml/ft/71622/FT_71622.html          1
Name: count, Length: 827, dtype: int64

In [33]:
# Eliminsmos url ficha tecnica porque si ponemos un indicador de ausencia, serían todas las filas 0 
# y si dejamos el url no aporta informacion adicional, actuaria como un identificador
df_clean = df_clean.drop(columns=["url_html_ficha_tecnica"])

In [ ]:
# Pasar identificadores a texto
df_clean["nregistro"] = df_clean["nregistro"].astype(str)
# Porque cn está guardado como decimal (float). Si lo pasas directamente a texto, se queda el .0 del final.
df_clean["cn"] = df_clean["cn"].astype(int).astype(str)

In [36]:
# estado_aut viene de la API de CIMA como un número muy grande
# Ese número son los milisegundos que han pasado desde el 1 de enero de 1970.
# pd.to_datetime lo convierte en una fecha normal, unit="ms" le dice a pandas que el número está en milisegundos.
df_clean["estado_aut"] = pd.to_datetime(df_clean["estado_aut"], unit="ms")
print(df_clean["estado_aut"])

0      2009-02-04 23:00:00
1      2009-02-04 23:00:00
2      2000-11-05 23:00:00
5      2024-04-22 09:44:08
6      2014-10-19 22:00:00
               ...
1548   2025-12-05 10:24:14
1553   2014-01-15 23:00:00
1566   1991-06-30 22:00:00
1567   2009-01-08 23:00:00
1568   2009-01-08 23:00:00
Name: estado_aut, Length: 827, dtype: datetime64[ns]

In [39]:
# palabras_seccion_4_4 se lee como texto porque 3 filas tienen escrito "no tiene sección 4.4".
# pd.to_numeric convierte la columna a número; con errors="coerce" lo que no se puede convertir (ese texto) pasa a ser nulo (NaN).
df_clean["palabras_seccion_4_4"] = pd.to_numeric(df_clean["palabras_seccion_4_4"], errors="coerce")
print("Nulos:", df_clean["palabras_seccion_4_4"].isna().sum())  

# Si un medicamento no tiene sección 4.4, consideramos que tiene 0 palabras en esa sección.
# fillna(0) sustituye los nulos por 0.
df_clean["palabras_seccion_4_4"] = df_clean["palabras_seccion_4_4"].fillna(0)

# Al pasar por nulos la columna se queda como decimal (1068.0), así que la devolvemos a entero.
# cuando una columna de números tiene algún NaN, pandas la convierte toda a decimal (float),
# aunque los números sean enteros.
df_clean["palabras_seccion_4_4"] = df_clean["palabras_seccion_4_4"].astype(int)

Nulos: 0

In [40]:
# Por defecto pandas solo enseña unas pocas filas y el resto lo sustituye por "...".
# Con None le decimos que muestre todas las filas, sin límite.
pd.set_option("display.max_rows", None)

# value_counts() muestra cada valor distinto de la columna y cuántas veces aparece, de más a menos repetido.
df_clean["dosis"].value_counts()

dosis
50 mg                                                 66
20 mg                                                 45
100 mg                                                41
150 mg                                                33
25 mg                                                 28
40 mg                                                 26
100 U/ml                                              25
75 mg                                                 25
2 mg                                                  24
10 mg                                                 23
300 mg                                                21
15 mg                                                 20
80 mg                                                 18
5 mg                                                  18
850 mg                                                17
50 mg/1.000 mg                                        17
40 mg simvastatina                                    16
50 mg/850 mg                                          16
20 mg simvastatina                                    14
1 mg                                                  14
4 mg                                                  13
2,5 mg                                                13
110 mg                                                11
10 mg simvastatina                                    10
50 mg losartan potasico                               10
100 mg losartan potasico                               9
40 MG                                                  9
30 mg                                                  9
60 mg                                                  9
50 MG                                                  8
25 MG                                                  7
50/1000 mg                                             7
20 MG                                                  7
50 mg/1000 mg                                          6
20 mg lisinopril                                       5
1000 mg                                                5
Desconocido                                            5
1.000 mg                                               4
100 UI/ml                                              4
10 MG                                                  4
0,5 mg                                                 4
80 MG                                                  4
1000/50 mg/mg                                          3
50/850 mg                                              3
0,25 mg                                                3
75 MG                                                  3
12,5 mg losartan potasico                              3
100 MG                                                 3
12,5 mg/1000 mg                                        3
0.5 mg                                                 3
12,5 mg/850 mg                                         2
50 - REVISAR mg                                        2
6 mg/ml                                                2
5 mg/1000 mg                                           2
50 mg captopril                                        2
2 MG                                                   2
25 mg captopril                                        2
1,5 mg                                                 2
12,5 mg                                                2
50 MG/1000 MG                                          2
100 mg/1.000 mg                                        2
128,9 mg                                               2
3 mg                                                   2
50 mg/ 850 mg                                          2
30 mg pioglitazona                                     2
30 MG                                                  2
5mg /850 mg                                            1
120 microgramos                                        1
75 mh clopidogrel                                      1
5mg /1.000 mg                                          1
Captopril 50 mg                                        1
2,5 MG linagliptina/850 MG metformina hidrocloruro     1
2,5 MG linagiptina/1000 MG metformina hidrocloruro     1
25 mg/ comprimido                                      1
10 mg/ comprimido                                      1
50 MG sitagliptina                                     1
25 MG Sitagliptina                                     1
25 mg/5 mg (empagliflozin/linagliptin) mg/mg           1
12,5 mg/30 mg                                          1
5 mg/10 mg                                             1
1 mg glucagón hidrocloruro                             1
20 mg lisinopril dihidrato                             1
5 mg lisinopril dihidrato                              1
15 MG                                                  1
0,1 mg/ml                                              1
10 mg/5 mg                                             1
10 mg/10 mg                                            1
2,5 mg/2,5 mg                                          1
2,5 mg/1,25 mg                                         1
7.5 - REVISAR mg                                       1
2.5 - REVISAR mg                                       1
5 mg ramipril                                          1
Ramipril, 2,5 mg                                       1
5 mg/5 mg                                              1
14 mg                                                  1
5 mg/2,5 mg                                            1
7 mg                                                   1
2,5 mg saxagliptina/850 mg metformina hidrocloruro     1
2,5mg saxagliptina/1000mg metformina hidrocloruro      1
100 mg losartan potasio                                1
12,5 MG                                                1
4 µg/ml                                                1
50 mg losartan potasio                                 1
200 U/ml                                               1
100 unidades/ml                                        1
50  mg                                                 1
5 mg linagiptina                                       1
50  - REVISAR mg                                       1
9 mg                                                   1
50 MG/850 MG                                           1
150 MG/1000 MG                                         1
5 mg/850 mg                                            1
100 mg acarbosa / comprimido                           1
50 mg Acarbosa /comprimido                             1
10 mg comprimidos                                      1
75 mg clopidogrel                                      1
15 mg rivaroxaban                                      1
20 mg rivaroxaban                                      1
6,25 mg                                                1
0,5 mg desmopresina acetato/ 0,5 ml                    1
0,2 mg                                                 1
60 MG                                                  1
2 MG / comprimido                                      1
4 MG / comprimido                                      1
15 mg / 850 mg                                         1
50 mg clortalidona                                     1
200 unidades/ml                                        1
100 UI/ML                                              1
150 mg irbesartan                                      1
300 mg irbesartan                                      1
75 mg irbesartan                                       1
150 MG                                                 1
75 mg clopidrogel                                      1
15mg-850mg                                             1
150 MG/850 MG                                          1
25 mg losartan potasico                                1
Desconocida                                            1
300 MG                                                 1
100 mg losartan                                        1
25 mg/ml                                               1
850 mg / comprimido                                    1
10 microgramos                                         1
50 mg losartan                                         1
850 MG                                                 1
15 mg pioglitazona                                     1
15 mg/850 mg                                           1
75 mg de Clopidogrel                                   1
75 mg de Clopidogrel como hidrogenosulfato             1
10 mg / comprimido                                     1
1000 MG                                                1
20 microgramos                                         1
1 MG                                                   1
0,5 MG                                                 1
15                                                     1
0,50 mg                                                1
20                                                     1
10 mg  simvastatina                                    1
50 mg/1000 mg\n                                        1
30 gm de pioglitazona + 2 mg de glimepirida            1
30 mg de pioglitazona + 4 mg de glimepirida            1
40 mg telmisartan                                      1
80 mg telmisartan                                      1
300 U/ml                                               1
300 unidades/ml                                        1
0,75 mg                                                1
50mg y 1000mg                                          1
850/50 mg/mg                                           1
Name: count, dtype: int64

In [42]:
# Tras estudiar en la celda anterior todos los posibles datos distintos que aparecian en las dosis de
# nuestros medicamentos, decidimos utilizar la IA generativa para poder obtener una fila resultante para
# cada caso concreto de nuestro dataset. El objetivo es poder obtener las dosis de los medicamentos 
# estandarizadas

# ============================================================
# LIMPIEZA Y ESTANDARIZACIÓN DE LA COLUMNA "dosis"
# Objetivo: dejar todas las dosis con el formato "número espacio unidad"
# (o "número unidad/número unidad" en combinaciones de dos principios activos)
# y después extraer el número.
# IMPORTANTE: esta celda va después de convertir nregistro a texto (paso 8).
# ============================================================


# PASO 1: corregir a mano las filas con valores desconocidos, incompletos o erróneos.
# El mismo texto ("Desconocido", "50 - REVISAR mg") corresponde a dosis distintas
# según la fila, así que no se puede reemplazar por texto: corregimos fila a fila usando nregistro.
# Justificación: la dosis correcta se ha sacado del nombre oficial del medicamento.
# ------------------------------------------------------------
correcciones_por_fila = {
    "150001": "15 mg",               # ACTOS 15 mg (ponía "Desconocido")
    "150009": "15 mg",               # ACTOS 15 mg (ponía "Desconocido")
    "150004": "30 mg",               # ACTOS 30 mg (ponía "Desconocido")
    "150010": "30 mg",               # ACTOS 30 mg (ponía "Desconocido")
    "98070001": "75 mg",             # ISCOVER 75 MG (ponía "Desconocido")
    "134006": "100 UI/ml",           # LANTUS 100 UNIDADES/ML (ponía "Desconocida")
    "1181265011": "2,5 mg/1000 mg",  # SEGLUROMET 2,5 MG/1.000 MG (ponía "2.5 - REVISAR mg")
    "1181265025": "7,5 mg/1000 mg",  # SEGLUROMET 7,5 MG/1.000 MG (ponía "7.5 - REVISAR mg")
    "86341": "50 mg/1000 mg",        # SITAGLIPTINA/METFORMINA STADA 50 MG/1.000 MG (ponía "50 - REVISAR mg")
    "86283": "50 mg/1000 mg",        # VILDAGLIPTINA/METFORMINA STADA 50 MG/1000 MG (ponía "50 - REVISAR mg")
    "86284": "50 mg/850 mg",         # VILDAGLIPTINA/METFORMINA STADA 50 MG/850 MG (ponía "50 - REVISAR mg")
    "9529002": "6 mg/ml",            # VICTOZA 6 MG/ML (ponía "60 mg", que es un error: la ficha técnica dice 6 mg por ml)
}

# Recorremos el diccionario y, para cada nregistro, sustituimos su dosis por la correcta
for nregistro, dosis_correcta in correcciones_por_fila.items():
    df_clean.loc[df_clean["nregistro"] == nregistro, "dosis"] = dosis_correcta


# ------------------------------------------------------------
# PASO 2: pasar a minúsculas y quitar espacios sobrantes.
# Así "50 MG" y "50 mg" quedan iguales y desaparecen los espacios dobles y los saltos de línea (\n).
# ------------------------------------------------------------
df_clean["dosis"] = df_clean["dosis"].str.lower()

# split() parte el texto por cualquier espacio, salto de línea o espacio doble,
# y join(" ") lo vuelve a unir con un solo espacio entre palabras
df_clean["dosis"] = df_clean["dosis"].str.split().str.join(" ")


# ------------------------------------------------------------
# PASO 3: quitar los nombres de principios activos y el texto sobrante.
# El principio activo ya está en la columna "pactivos", así que en "dosis" sobra.
# Ponemos primero los textos más largos: si quitáramos antes "losartan",
# en "losartan potasico" quedaría suelto "potasico".
# ------------------------------------------------------------
quitar = [
    "como hidrogenosulfato",
    "metformina hidrocloruro",
    "glucagón hidrocloruro",
    "losartan potasico",
    "losartan potasio",
    "losartan",
    "lisinopril dihidrato",
    "lisinopril",
    "simvastatina",
    "irbesartan",
    "telmisartan",
    "rivaroxaban",
    "pioglitazona",
    "glimepirida",
    "captopril",
    "clopidogrel",
    "clopidrogel",                         # errata del original
    "clortalidona",
    "ramipril,",                           # "Ramipril, 2,5 mg" (también hay que quitar la coma)
    "ramipril",
    "acarbosa",
    "sitagliptina",
    "linagliptina",
    "linagiptina",                         # errata del original
    "saxagliptina",
    "(empagliflozin/linagliptin) mg/mg",
    "/ comprimido",
    "/comprimido",
    "comprimidos",
    " de ",                                # "30 mg de pioglitazona" -> "30 mg"
]

# Recorremos la lista y vamos borrando cada texto (lo cambiamos por un espacio)
for texto in quitar:
    df_clean["dosis"] = df_clean["dosis"].str.replace(texto, " ", regex=False)

# Al borrar quedan espacios dobles o al principio/final: los limpiamos otra vez
df_clean["dosis"] = df_clean["dosis"].str.split().str.join(" ")


# ------------------------------------------------------------
# PASO 4: corregir casos concretos con un diccionario.
# Son valores únicos que no siguen ninguna regla general; cada línea es un caso justificado.
# ------------------------------------------------------------
casos_concretos = {
    "75 mh": "75 mg",                    # errata: mh -> mg
    "30 gm + 2 mg": "30 mg/2 mg",        # errata: gm -> mg (TANDEMACT 30 mg/2 mg)
    "1000/50 mg/mg": "50 mg/1000 mg",    # orden invertido (RISTFOR, VELMETIA, ZOMARIST 50 MG/1000 MG)
    "850/50 mg/mg": "50 mg/850 mg",      # orden invertido (ZOMARIST 50 mg/850 mg)
    "50/1000 mg": "50 mg/1000 mg",       # falta la unidad en el primer número
    "50/850 mg": "50 mg/850 mg",         # falta la unidad en el primer número
    "15": "15 mg",                       # sin unidad (RIXACAM 15 MG)
    "20": "20 mg",                       # sin unidad (RIXACAM 20 MG)
    "0,5 mg desmopresina acetato/ 0,5 ml": "0,1 mg/ml",  # el nombre del medicamento dice 0,1 mg/ml
    "10 microgramos": "0,01 mg",         # 1 mg = 1000 microgramos
    "20 microgramos": "0,02 mg",
    "120 microgramos": "0,12 mg",
    "4 µg/ml": "0,004 mg/ml",            # µg es otra forma de escribir microgramos
}

# replace con un diccionario cambia los valores que coinciden EXACTAMENTE con una clave
df_clean["dosis"] = df_clean["dosis"].replace(casos_concretos)


# ------------------------------------------------------------
# PASO 5: poner un espacio entre el número y "mg" ("15mg" -> "15 mg").
# Es una expresión regular: (\d) significa "un número" y \1 es "ese mismo número".
# Se lee: "donde haya un número pegado a mg, escribe el número, un espacio y mg".
# ------------------------------------------------------------
df_clean["dosis"] = df_clean["dosis"].str.replace(r"(\d)mg", r"\1 mg", regex=True)


# ------------------------------------------------------------
# PASO 6: usar "/" como único separador de combinaciones.
# Las combinaciones de dos principios activos venían separadas con "+", "y", "-"
# o con espacios alrededor de "/".
# ------------------------------------------------------------
separadores = {
    " + ": "/",     # "30 mg + 4 mg"    -> "30 mg/4 mg"
    " y ": "/",     # "50 mg y 1000 mg" -> "50 mg/1000 mg"
    "-": "/",       # "15 mg-850 mg"    -> "15 mg/850 mg"
    " / ": "/",     # "15 mg / 850 mg"  -> "15 mg/850 mg"
    "/ ": "/",      # "50 mg/ 850 mg"   -> "50 mg/850 mg"
    " /": "/",      # "5 mg /850 mg"    -> "5 mg/850 mg"
}
for viejo, nuevo in separadores.items():
    df_clean["dosis"] = df_clean["dosis"].str.replace(viejo, nuevo, regex=False)


# ------------------------------------------------------------
# PASO 7: unificar el separador decimal.
# Python solo entiende el punto como decimal. Hay que quitar PRIMERO el punto de miles
# de "1.000"; si no, después se leería como 1.0.
# ------------------------------------------------------------
# 1) "1.000" es mil (punto de miles), no uno con decimales
df_clean["dosis"] = df_clean["dosis"].str.replace("1.000", "1000", regex=False)

# 2) La coma decimal española pasa a punto: "2,5 mg" -> "2.5 mg"
df_clean["dosis"] = df_clean["dosis"].str.replace(",", ".", regex=False)

# 3) "0.50 mg" es lo mismo que "0.5 mg"
df_clean["dosis"] = df_clean["dosis"].str.replace("0.50 mg", "0.5 mg", regex=False)


# ------------------------------------------------------------
# PASO 8: unificar las unidades de insulina.
# "U/ml", "UI/ml" y "unidades/ml" significan lo mismo: unidades internacionales por ml.
# ------------------------------------------------------------
df_clean["dosis"] = df_clean["dosis"].str.replace("unidades/ml", "UI/ml", regex=False)
df_clean["dosis"] = df_clean["dosis"].str.replace("ui/ml", "UI/ml", regex=False)
df_clean["dosis"] = df_clean["dosis"].str.replace("u/ml", "UI/ml", regex=False)


# ------------------------------------------------------------
# PASO 9: marcar qué dosis están expresadas "por ml" (líquidos e insulinas).
# Lo hacemos ANTES de pasarlo todo a mg para no perder esta información:
# en un comprimido los mg son por comprimido; en un líquido, por cada ml.
# ------------------------------------------------------------
df_clean["dosis_por_ml"] = 0
df_clean.loc[df_clean["dosis"].str.contains("/ml"), "dosis_por_ml"] = 1


# ------------------------------------------------------------
# PASO 10: pasar las insulinas de UI/ml a mg/ml.
# Las UI (unidades internacionales) miden actividad, no peso, y la equivalencia depende
# del tipo de insulina. La sacamos de la sección 2 de la ficha técnica de cada una
# ("1 ml contiene 100 unidades de insulina ... (equivalente a X mg)").
# Las fichas de Humulina no indican los mg; usamos la equivalencia de la insulina humana
# de Actrapid, Insulatard y Mixtard (100 UI = 3,5 mg).
# ------------------------------------------------------------
# Diccionario: principio activo -> mg que hay en 100 UI
mg_por_100_ui = {
    "INSULINA ASPARTA": 3.5,                                                   # Fiasp, NovoRapid
    "INSULINA ASPARTA, INSULINA ASPARTA PROTAMINA+": 3.5,                      # NovoMix
    "INSULINA DEGLUDEC": 3.66,                                                 # Tresiba
    "INSULINA DETEMIR": 14.2,                                                  # Levemir
    "INSULINA GLARGINA": 3.64,                                                 # Lantus, Abasaglar, Semglee, Toujeo
    "INSULINA GLULISINA": 3.49,                                                # Apidra
    "INSULINA LISPRO": 3.5,                                                    # Humalog
    "INSULINA LISPRO, INSULINA LISPRO PROTAMINA": 3.5,                         # Humalog Mix
    "INSULINA HUMANA": 3.5,                                                    # Humulina Regular, Humulina 30:70
    "INSULINA HUMANA ISOFANA": 3.5,                                            # Insulatard
    "INSULINA ISOFANA HUMANA PRB": 3.5,                                        # Humulina NPH
    "INSULINA SOLUBLE NEUTRA": 3.5,                                            # Actrapid
    "INSULINA SOLUBLE NEUTRA HUMANA PRB, INSULINA ISOFANA HUMANA PRB": 3.5,    # Mixtard
}

# Filas que son insulina (su dosis está en UI/ml)
es_insulina = df_clean["dosis"].str.contains("UI/ml")

# Número de UI por ml: el texto antes del espacio. "100 UI/ml" -> 100
ui_por_ml = df_clean.loc[es_insulina, "dosis"].str.split(" ").str[0].astype(float)

# Buscamos en el diccionario los mg por 100 UI de cada insulina según su principio activo
factor = df_clean.loc[es_insulina, "pactivos"].map(mg_por_100_ui)
print("Insulinas sin equivalencia en el diccionario:", factor.isna().sum())   # tiene que salir 0

# Regla de tres: si 100 UI son "factor" mg, entonces "ui_por_ml" UI son ui_por_ml * factor / 100 mg
mg_por_ml = (ui_por_ml * factor / 100).round(2)

# Escribimos el resultado con el formato "número mg/ml".
# "{:g}".format quita los decimales que sobran (7.0 -> "7", 3.66 -> "3.66")
df_clean.loc[es_insulina, "dosis"] = mg_por_ml.map("{:g}".format) + " mg/ml"


# ------------------------------------------------------------
# PASO 11: dejar todo como "mg".
# Ya está todo en mg o en mg/ml. Quitamos el "/ml" para que todas las dosis tengan el mismo formato;
# la columna dosis_por_ml (paso 9) guarda que esas dosis son por cada ml.
# ------------------------------------------------------------
df_clean["dosis"] = df_clean["dosis"].str.replace("mg/ml", "mg", regex=False)


# ------------------------------------------------------------
# COMPROBACIÓN: todas las dosis deben ser "número mg" o "número mg/número mg".
# ------------------------------------------------------------
pd.set_option("display.max_rows", None)          # mostrar todas las filas, sin "..."
print(df_clean["dosis"].value_counts().sort_index())
pd.reset_option("display.max_rows")               # volvemos al límite por defecto

# Contamos las filas que NO terminan en "mg" (tiene que salir 0)
print("Filas que no están en mg:", (~df_clean["dosis"].str.endswith(" mg")).sum())


# ------------------------------------------------------------
# PASO 12: quedarnos con el número de la dosis.
# En las combinaciones guardamos también el segundo número para no perder información.
# ------------------------------------------------------------
# Número de la dosis: el texto antes del primer espacio. "50 mg/1000 mg" -> "50"
df_clean["dosis_numero"] = df_clean["dosis"].str.split(" ").str[0].astype(float)

# Segundo número (solo en combinaciones como "50 mg/1000 mg" -> 1000).
# Cogemos lo que hay después de "/" y luego lo que hay antes del espacio.
# Si no hay "/", str[1] da nulo: to_numeric lo deja como NaN y fillna lo pasa a 0.
segunda_parte = df_clean["dosis"].str.split("/").str[1].str.split(" ").str[0]
df_clean["dosis_numero_2"] = pd.to_numeric(segunda_parte, errors="coerce").fillna(0)

# Comprobamos el resultado
df_clean[["nombre", "dosis", "dosis_numero", "dosis_numero_2", "dosis_por_ml"]].head(10)

Insulinas sin equivalencia en el diccionario: 0
dosis
0.004 mg            1
0.01 mg             1
0.02 mg             1
0.1 mg              2
0.12 mg             1
0.2 mg              1
0.25 mg             3
0.5 mg              9
0.75 mg             1
1 mg               16
1.5 mg              2
10 mg              41
10 mg/10 mg         1
10 mg/5 mg          1
10.92 mg            2
100 mg             56
100 mg/1000 mg      2
1000 mg            10
110 mg             11
12.5 mg             6
12.5 mg/1000 mg     3
12.5 mg/30 mg       1
12.5 mg/850 mg      2
128.9 mg            2
14 mg               1
14.2 mg             2
15 mg              26
15 mg/850 mg        3
150 mg             35
150 mg/1000 mg      1
150 mg/850 mg       1
2 mg               27
2.5 mg             14
2.5 mg/1.25 mg      1
2.5 mg/1000 mg      3
2.5 mg/2.5 mg       1
2.5 mg/850 mg       2
20 mg              74
25 mg              41
25 mg/5 mg          1
3 mg                2
3.49 mg             2
3.5 mg             21
3.64 mg             5
3.66 mg             2
30 mg              15
30 mg/2 mg          1
30 mg/4 mg          1
300 mg             23
4 mg               14
40 mg              52
5 mg               21
5 mg/10 mg          1
5 mg/1000 mg        3
5 mg/2.5 mg         1
5 mg/5 mg           1
5 mg/850 mg         2
50 mg              93
50 mg/1000 mg      39
50 mg/850 mg       24
6 mg                3
6.25 mg             1
60 mg               9
7 mg                2
7.32 mg             1
7.5 mg/1000 mg      1
75 mg              35
80 mg              23
850 mg             19
9 mg                1
Name: count, dtype: int64
Filas que no están en mg: 0

,nombre,dosis,dosis_numero,dosis_numero_2,dosis_por_ml
0,ACARBOSA TECNIGEN 100 mg COMPRIMIDOS,100 mg,100.00,0.0,0
1,ACARBOSA TECNIGEN 50 mg COMPRIMIDOS,50 mg,50.00,0.0,0
2,ACTRAPID INNOLET 100 UI/ML SOLUCION INYECTABLE...,3.5 mg,3.50,0.0,1
5,BIGETRA 150 MG CAPSULAS DURAS,150 mg,150.00,0.0,0
6,BYDUREON 2 MG POLVO Y DISOLVENTE PARA SUSPENSI...,2 mg,2.00,0.0,0
7,BYETTA 10 MICROGRAMOS SOLUCION INYECTABLE EN P...,0.25 mg,0.25,0.0,0
8,BYETTA 5 MICROGRAMOS SOLUCION INYECTABLE EN PL...,0.25 mg,0.25,0.0,0
9,CAPTOPRIL CINFA 25 mg COMPRIMIDOS EFG,25 mg,25.00,0.0,0
10,CAPTOPRIL CINFA 50 mg COMPRIMIDOS EFG,50 mg,50.00,0.0,0
12,CAPTOPRIL NORMON 50 mg COMPRIMIDOS EFG,50 mg,50.00,0.0,0

In [43]:
# tratamiento_larga_duracion de Si/No a 1/0
df_clean["tratamiento_larga_duracion"] = df_clean["tratamiento_larga_duracion"].map({"SI": 1, "NO": 0})
df_clean["tratamiento_larga_duracion"].value_counts()

tratamiento_larga_duracion
0    551
1    276
Name: count, dtype: int64

In [45]:
df_clean["forma_farmaceutica_simplificada"].value_counts()

forma_farmaceutica_simplificada
COMPRIMIDO                          717
INYECTABLE                           51
CAPSULA                              35
COMPRIMIDO LIBERACION MODIFICADA     19
PRODUCTO USO NASAL                    3
COMPRIMIDO SUBLINGUAL                 1
SOLUCIÓN/SUSPENSIÓN ORAL              1
Name: count, dtype: int64

In [46]:
# Agrupar forma_farmaceutica_simplificada
grupos_forma = {
    "COMPRIMIDO": "COMPRIMIDO",
    "COMPRIMIDO LIBERACION MODIFICADA": "COMPRIMIDO",
    "COMPRIMIDO SUBLINGUAL": "COMPRIMIDO",
    "CAPSULA": "CAPSULA",
    "INYECTABLE": "INYECTABLE",
    "PRODUCTO USO NASAL": "OTRA",
    "SOLUCIÓN/SUSPENSIÓN ORAL": "OTRA",
}

# .map recorre la columna fila por fila y traduce cada valor usando el diccionario.
df_clean["forma_farmaceutica_simplificada"] = df_clean["forma_farmaceutica_simplificada"].map(grupos_forma)
df_clean["forma_farmaceutica_simplificada"].value_counts(dropna=False)

forma_farmaceutica_simplificada
COMPRIMIDO    737
INYECTABLE     51
CAPSULA        35
OTRA            4
Name: count, dtype: int64

In [47]:
df_clean["vias_administracion"].value_counts()

vias_administracion
VÍA ORAL                                              772
VÍA SUBCUTÁNEA                                         41
VÍA INTRAVENOSA, VÍA SUBCUTÁNEA                         4
VÍA INTRAMUSCULAR, VÍA INTRAVENOSA, VÍA SUBCUTÁNEA      3
VÍA NASAL                                               3
VÍA INTRAMUSCULAR, VÍA SUBCUTÁNEA                       3
VÍA SUBLINGUAL                                          1
Name: count, dtype: int64

In [48]:
# Agrupar vias_administracion como antes
# Diccionario: vía original -> grupo
# Las claves tienen que estar escritas EXACTAMENTE igual que en los datos (con tildes y comas)
grupos_via = {
    "VÍA ORAL": "ORAL",
    "VÍA SUBLINGUAL": "ORAL",                                         
    "VÍA SUBCUTÁNEA": "INYECTABLE",
    "VÍA INTRAVENOSA, VÍA SUBCUTÁNEA": "INYECTABLE",                 
    "VÍA INTRAMUSCULAR, VÍA SUBCUTÁNEA": "INYECTABLE",
    "VÍA INTRAMUSCULAR, VÍA INTRAVENOSA, VÍA SUBCUTÁNEA": "INYECTABLE",
    "VÍA NASAL": "NASAL",
}

# .map traduce cada valor usando el diccionario; lo que no esté en el diccionario pasa a NaN
df_clean["vias_administracion"] = df_clean["vias_administracion"].map(grupos_via)

# Comprobamos que no ha quedado ningún NaN (si sale alguno, falta una clave en el diccionario)
df_clean["vias_administracion"].value_counts(dropna=False)

vias_administracion
ORAL          773
INYECTABLE     51
NASAL           3
Name: count, dtype: int64

In [49]:
df_clean = df_clean.reset_index(drop=True)
print(df_clean.shape)               # (827, 30)
print(df_clean.isna().sum().sum())  # 0
df_clean.dtypes

(827, 29)
1240

nregistro                                  object
nombre                                     object
pactivos                                   object
labtitular                                 object
labcomercializador                         object
cn                                         object
dosis                                      object
forma_farmaceutica_simplificada            object
estado_aut                         datetime64[ns]
estado_rev                                float64
comercializado                              int64
generico                                    int64
afecta_conduccion                           int64
biosimilar                                  int64
url_foto_materiales                        object
num_registros_atc                           int64
num_principios_activos                      int64
num_excipientes                             int64
vias_administracion                        object
palabras_seccion_4_4                        int64
numero_tablas                               int64
indicador_riesgo_severo                     int64
estado                                     object
precio_pvp_iva                            float64
tratamiento_larga_duracion                  int64
dosis_numero                              float64
dosis_unidad                               object
dosis_numero_2                            float64
dosis_por_ml                                int64
dtype: object

In [ ]:
df_clean.to_csv("../data/HU4_medicamentos_diabetes_limpio.csv", index=False, encoding="utf-8-sig")